Repository googleapis/java-kms, pull requests merged in 2020-12, with the labels that each got.

#347 chore: Update publish_javadoc.sh
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: cloudkms, automerge, cla: yes, context: full

#333 chore: give api-kms push access
  .github/sync-repo-settings.yaml
Labels: api: cloudkms, cla: yes

#356 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudkms, automerge, cla: yes

#365 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudkms, automerge, cla: yes

#366 ci(java): ignore bot users for generate-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: cloudkms, automerge, cla: yes, context: full

#367 chore(java): remove formatter action
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: cloudkms, automerge, cla: yes, context: full, merge
