Repository googleapis/java-kms, pull requests merged in 2020-09, with the labels that each got.

#257 [CHANGE ME] Re-generated to pick up changes from synthtool.
  README.md
  synth.metadata
Labels: api: cloudkms, cla: yes, context: partial

#258 chore: regenerate README
  README.md
  synth.metadata
Labels: api: cloudkms, cla: yes, context: none

#261 chore: regenerate templates
  .github/CODEOWNERS
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#272 build(java): use yoshi-approver token for auto-approve
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#271 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: cloudkms, automerge, cla: yes

#277 chore: regenerate templates
  .github/readme/synth.py
  .github/workflows/auto-release.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#279 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
