Repository googleapis/java-kms, pull requests merged in 2020-08, with the labels that each got.

#230 chore: regenerate common templates
  .kokoro/continuous/dependencies.cfg
  .kokoro/continuous/integration.cfg
  .kokoro/continuous/java11.cfg
  .kokoro/continuous/java7.cfg
  .kokoro/continuous/java8-osx.cfg
  .kokoro/continuous/java8-win.cfg
  .kokoro/continuous/lint.cfg
  .kokoro/continuous/propose_release.cfg
  .kokoro/continuous/samples.cfg
  .kokoro/nightly/dependencies.cfg
  .kokoro/nightly/lint.cfg
  README.md
  samples/snippets/pom.xml
  synth.metadata
Labels: automerge, cla: yes, context: partial

#232 build: update dependencies check to only check for runtime and compile scopes
  .kokoro/dependencies.sh
  synth.metadata
Labels: cla: yes, context: full

#234 feat: add client integrity verification fields to the KMS protos
  README.md
  google-cloud-kms/src/main/java/com/google/cloud/kms/v1/KeyManagementServiceClient.java
  google-cloud-kms/src/test/java/com/google/cloud/kms/v1/KeyManagementServiceClientTest.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/AsymmetricDecryptRequest.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/AsymmetricDecryptRequestOrBuilder.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/AsymmetricDecryptResponse.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/AsymmetricDecryptResponseOrBuilder.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/AsymmetricSignRequest.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/AsymmetricSignRequestOrBuilder.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/AsymmetricSignResponse.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/AsymmetricSignResponseOrBuilder.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/CryptoKey.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/DecryptRequest.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/DecryptRequestOrBuilder.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/DecryptResponse.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/DecryptResponseOrBuilder.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/EncryptRequest.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/EncryptRequestOrBuilder.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/EncryptResponse.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/EncryptResponseOrBuilder.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/KmsProto.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/KmsResourcesProto.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/PublicKey.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/PublicKeyOrBuilder.java
  proto-google-cloud-kms-v1/src/main/proto/google/cloud/kms/v1/resources.proto
  proto-google-cloud-kms-v1/src/main/proto/google/cloud/kms/v1/service.proto
  synth.metadata
Labels: cla: yes, context: partial

#238 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#240 chore: regenerate README
  README.md
  synth.metadata
Labels: cla: yes, context: none

#246 samples: add presubmit lint check
  .github/workflows/samples.yaml
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: partial

#247 build: temporarily disable reporting to unblock releases
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: cloudkms, cla: yes, context: full

#248 build: switch to release publish app
  .kokoro/release/stage.cfg
  .kokoro/release/stage.sh
Labels: cla: yes
