Repository googleapis/java-kms, pull requests merged in 2020-06, with the labels that each got.

#179 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#180 chore: regenerate with updated protoc
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/AsymmetricDecryptRequest.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/AsymmetricDecryptResponse.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/AsymmetricSignRequest.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/AsymmetricSignResponse.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/CreateCryptoKeyRequest.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/CreateCryptoKeyVersionRequest.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/CreateImportJobRequest.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/CreateKeyRingRequest.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/CryptoKey.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/CryptoKeyVersion.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/CryptoKeyVersionTemplate.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/DecryptRequest.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/DecryptResponse.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/DestroyCryptoKeyVersionRequest.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/Digest.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/EncryptRequest.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/EncryptResponse.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/ExternalProtectionLevelOptions.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/GetCryptoKeyRequest.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/GetCryptoKeyVersionRequest.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/GetImportJobRequest.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/GetKeyRingRequest.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/GetPublicKeyRequest.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/ImportCryptoKeyVersionRequest.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/ImportJob.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/KeyOperationAttestation.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/KeyRing.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/ListCryptoKeyVersionsRequest.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/ListCryptoKeyVersionsResponse.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/ListCryptoKeysRequest.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/ListCryptoKeysResponse.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/ListImportJobsRequest.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/ListImportJobsResponse.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/ListKeyRingsRequest.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/ListKeyRingsResponse.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/LocationMetadata.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/ProtectionLevel.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/PublicKey.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/RestoreCryptoKeyVersionRequest.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/UpdateCryptoKeyPrimaryVersionRequest.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/UpdateCryptoKeyRequest.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/UpdateCryptoKeyVersionRequest.java
  synth.metadata
Labels: automerge, cla: yes, context: full

#182 chore(java_templates): add default CODEOWNERS files for samples reviews
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#185 chore: turn on renovate-bot master issue for java repos
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#184 docs: change relative URLs to absolute URLs to fix broken links.
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/CryptoKey.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/CryptoKeyOrBuilder.java
  proto-google-cloud-kms-v1/src/main/proto/google/cloud/kms/v1/resources.proto
  synth.metadata
Labels: automerge, cla: yes, context: full

#187 build(java): skip lint on samples directory
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#192 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#193 fix: migrate kms/v1 to grpc_service_config
  google-cloud-kms/src/main/java/com/google/cloud/kms/v1/KeyManagementServiceClient.java
  google-cloud-kms/src/main/java/com/google/cloud/kms/v1/KeyManagementServiceSettings.java
  google-cloud-kms/src/main/java/com/google/cloud/kms/v1/package-info.java
  google-cloud-kms/src/main/java/com/google/cloud/kms/v1/stub/GrpcKeyManagementServiceStub.java
  google-cloud-kms/src/main/java/com/google/cloud/kms/v1/stub/KeyManagementServiceStub.java
  google-cloud-kms/src/main/java/com/google/cloud/kms/v1/stub/KeyManagementServiceStubSettings.java
  google-cloud-kms/src/test/java/com/google/cloud/kms/v1/KeyManagementServiceClientTest.java
  synth.metadata
Labels: automerge, cla: yes, context: full

#197 ci: switch to secret manager for sample/integration tests
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#203 feat(deps): adopt flatten plugin and google-cloud-shared-dependencies
  .gitignore
  google-cloud-kms/pom.xml
  grpc-google-cloud-kms-v1/pom.xml
  pom.xml
  proto-google-cloud-kms-v1/pom.xml
Labels: cla: yes

#202 chore: update README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#215 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none
