Repository googleapis/java-kms, pull requests merged in 2021-09, with the labels that each got.

#602 feat: add support for Key Reimport
  google-cloud-kms/src/main/java/com/google/cloud/kms/v1/KeyManagementServiceClient.java
  google-cloud-kms/src/test/java/com/google/cloud/kms/v1/KeyManagementServiceClientTest.java
  grpc-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/KeyManagementServiceGrpc.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/CryptoKeyVersion.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/CryptoKeyVersionOrBuilder.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/ImportCryptoKeyVersionRequest.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/ImportCryptoKeyVersionRequestOrBuilder.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/KmsProto.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/KmsResourcesProto.java
  proto-google-cloud-kms-v1/src/main/proto/google/cloud/kms/v1/resources.proto
  proto-google-cloud-kms-v1/src/main/proto/google/cloud/kms/v1/service.proto
  synth.metadata
Labels: cla: yes, api: cloudkms, context: full

#605 chore(java): install maven 3.8.1 at runtime
  .github/workflows/ci.yaml
  synth.metadata
Labels: kokoro:force-run, cla: yes, api: cloudkms, automerge, context: full

#604 chore: migrate to owlbot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  README.md
  google-cloud-kms-bom/pom.xml
  google-cloud-kms/pom.xml
  owlbot.py
  pom.xml
  versions.txt
Labels: cla: yes, api: cloudkms, automerge

#608 chore(java): update windows build
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, api: cloudkms, context: full

#612 chore: fix owlbot.yaml
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  .github/trusted-contribution.yml
  .kokoro/release/common.sh
  .kokoro/release/drop.sh
  .kokoro/release/promote.sh
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.sh
  .kokoro/release/stage.sh
  .kokoro/trampoline.sh
Labels: cla: yes, api: cloudkms, automerge

#611 chore: remove readme autosynth config
  .github/readme/synth.metadata/synth.metadata
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: cla: yes, api: cloudkms

#630 chore: make owlbot check required
  .github/sync-repo-settings.yaml
  README.md
Labels: cla: yes, api: cloudkms, automerge

#634 chore: change branch master to main in sync-repo-settings.yaml
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: cloudkms, automerge

#623 chore: relocate owl bot post processor
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  README.md
Labels: cla: yes, api: cloudkms
