Repository googleapis/java-kms, pull requests merged in 2021-07, with the labels that each got.

#531 feat: add ECDSA secp256k1 to the list of supported algorithms
  google-cloud-kms/src/main/java/com/google/cloud/kms/v1/KeyManagementServiceClient.java
  grpc-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/KeyManagementServiceGrpc.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/CryptoKeyName.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/CryptoKeyVersion.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/CryptoKeyVersionName.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/ImportJobName.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/KeyRingName.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/KmsResourcesProto.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/LocationName.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/PublicKeyName.java
  proto-google-cloud-kms-v1/src/main/proto/google/cloud/kms/v1/resources.proto
  proto-google-cloud-kms-v1/src/main/proto/google/cloud/kms/v1/service.proto
  synth.metadata
Labels: api: cloudkms, automerge, cla: yes, context: full

#536 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudkms, automerge, cla: yes

#539 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudkms, automerge, cla: yes

#541 chore: remove distributionManagement section
  pom.xml
Labels: api: cloudkms, automerge, cla: yes

#542 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#543 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudkms, automerge, cla: yes

#544 chore: remove distributionManagement section
  google-cloud-kms-bom/pom.xml
Labels: api: cloudkms, automerge, cla: yes

#547 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudkms, automerge, cla: yes

#546 chore: remove All rights reserved clause from java.header
  java.header
  synth.metadata
Labels: api: cloudkms, automerge, cla: yes, context: full

#548 chore: add dependencyDashboardLabels to renovate.json
  renovate.json
  synth.metadata
Labels: api: cloudkms, automerge, cla: yes, context: full

#550 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudkms, automerge, cla: yes

#553 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudkms, automerge, cla: yes

#554 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudkms, automerge, cla: yes

#558 build: configure branch java7 as a release branch
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: api: cloudkms, automerge, cla: yes

#559 feat: configure initial sp version
  .github/workflows/ci.yaml
Labels: api: cloudkms, automerge, cla: yes
