Repository googleapis/java-kms, pull requests merged in 2021-08, with the labels that each got.

#555 chore: remove java 7 units check
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, api: cloudkms, automerge, context: full

#564 chore: remove java7 units check from required checks in master
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: cloudkms, automerge

#561 feat!: release gapic-generator-java v2.0.0
  google-cloud-kms/src/main/java/com/google/cloud/kms/v1/KeyManagementServiceClient.java
  google-cloud-kms/src/main/java/com/google/cloud/kms/v1/KeyManagementServiceSettings.java
  google-cloud-kms/src/main/java/com/google/cloud/kms/v1/stub/GrpcKeyManagementServiceStub.java
  google-cloud-kms/src/main/java/com/google/cloud/kms/v1/stub/KeyManagementServiceStubSettings.java
  google-cloud-kms/src/test/java/com/google/cloud/kms/v1/KeyManagementServiceClientTest.java
  proto-google-cloud-kms-v1/clirr-ignored-differences.xml
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/PublicKeyName.java
  synth.metadata
Labels: cla: yes, api: cloudkms, automerge, context: full

#572 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: cloudkms, automerge

#574 build(java): use ENABLE_FLAKYBOT env variable
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  synth.metadata
Labels: cla: yes, api: cloudkms, automerge, context: full

#578 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: cloudkms, automerge

#579 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: cloudkms, automerge

#581 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: cloudkms, automerge

#582 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: cloudkms, automerge

#589 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: cloudkms, automerge

#588 ci: removing linkage-monitor from the required checks
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: cloudkms, automerge

#597 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: cloudkms, automerge

#601 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: cloudkms, automerge

#595 chore: update gapic-generator-java version to 2.1.0
  google-cloud-kms/src/main/java/com/google/cloud/kms/v1/stub/KeyManagementServiceStubSettings.java
  synth.metadata
Labels: cla: yes, api: cloudkms, context: full

#599 build(java): update renovate config to mark conformance tests as a test commit type
  renovate.json
  synth.metadata
Labels: cla: yes, api: cloudkms, automerge, context: full
