Repository googleapis/java-kms, pull requests merged in 2021-05, with the labels that each got.

#477 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: cloudkms, automerge, cla: yes, context: none

#478 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: cloudkms, automerge, cla: yes

#487 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudkms, automerge, cla: yes

#488 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: cloudkms, automerge, cla: yes, context: full

#492 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudkms, automerge, cla: yes

#493 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: cloudkms, automerge, cla: yes, context: full

#495 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: cloudkms, automerge, cla: yes, context: full

#498 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: cloudkms, automerge, cla: yes, context: full

#504 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudkms, automerge, cla: yes

#505 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudkms, automerge, cla: yes

#502 chore: migrate KMS to the Java microgenerator
  google-cloud-kms/src/main/java/com/google/cloud/kms/v1/KeyManagementServiceClient.java
  google-cloud-kms/src/main/java/com/google/cloud/kms/v1/KeyManagementServiceSettings.java
  google-cloud-kms/src/main/java/com/google/cloud/kms/v1/gapic_metadata.json
  google-cloud-kms/src/main/java/com/google/cloud/kms/v1/package-info.java
  google-cloud-kms/src/main/java/com/google/cloud/kms/v1/stub/GrpcKeyManagementServiceCallableFactory.java
  google-cloud-kms/src/main/java/com/google/cloud/kms/v1/stub/GrpcKeyManagementServiceStub.java
  google-cloud-kms/src/main/java/com/google/cloud/kms/v1/stub/KeyManagementServiceStub.java
  google-cloud-kms/src/main/java/com/google/cloud/kms/v1/stub/KeyManagementServiceStubSettings.java
  google-cloud-kms/src/test/java/com/google/cloud/kms/v1/KeyManagementServiceClientTest.java
  google-cloud-kms/src/test/java/com/google/cloud/kms/v1/MockKeyManagementService.java
  google-cloud-kms/src/test/java/com/google/cloud/kms/v1/MockKeyManagementServiceImpl.java
  google-cloud-kms/src/test/java/com/google/iam/v1/MockIAMPolicy.java
  google-cloud-kms/src/test/java/com/google/iam/v1/MockIAMPolicyImpl.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/CryptoKeyName.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/CryptoKeyVersionName.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/ImportJobName.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/KeyRingName.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/LocationName.java
  proto-google-cloud-kms-v1/src/main/java/com/google/cloud/kms/v1/PublicKeyName.java
  synth.metadata
Labels: api: cloudkms, automerge, cla: yes, context: full

#506 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudkms, automerge, cla: yes
